spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bjftview_protect?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678


##log4j 日志输出
logging:
  level:
    root: info