
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bjftview_protect?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678






##log4j 日志输出
logging:
  level:
    root: info
#  config: classpath:log4j2.xml #log4j.properties配置文件（log4j后缀为*.properties）
##  # path 和 name 同时启用，起作用的是name
#  file:
#    path: /Users/wangshuo/IdeaProjects/sg/bjftView-protect #设置存储在本地日志路径
#    name: logs #设置存储在本地日志名称（日志文件默认存储在项目根目录）